global:
  username: hcmus-polars
  project_name: hcmus-shrec23-textANIMAR
  name: point-cloud
  save_dir: "./runs"
  verbose: true
  pretrained: null
  resume: null
  SEED: 1337
dataset:
  train:
    params:
      text_queries_path: "dataset/csv/TextQuery_Train.csv"
      pc_ids_path: "dataset/csv/ModelID.csv"
      pc_dir: "dataset/PC_OBJ"
      ground_truth_path: "dataset/csv/TextQuery_GT_Train.csv"
  val:
    params:
      text_queries_path: "dataset/csv/TextQuery_Train.csv"
      pc_ids_path: "dataset/csv/ModelID.csv"
      pc_dir: "dataset/PC_OBJ"
      ground_truth_path: "dataset/csv/TextQuery_GT_Validation.csv"
data_loader:
  train:
    params:
      batch_size: 4
      num_workers: 2
      shuffle: true
  val:
    params:
      num_workers: 2
      batch_size: 2
model:
  name: "BaselineModel"
  params:
    embed_dim: 128
trainer:
  lr: 0.001
  use_fp16: true
  debug: false
  num_epochs: 10000
  clip_grad: 10.0
  evaluate_interval: 1
  log_interval: 1
  save_interval: 1000
callbacks:
  - name: ModelCheckpoint
    params:
      filename: "baseline-{epoch}-{train_loss:.4f}-{val_loss:.4f}"
      monitor: "val_loss"
      verbose: True
      save_top_k: 3
      mode: min
