global:
  username: hcmus-polars
  project_name: hcmus-shrec23-textANIMAR
  name: point-cloud
  save_dir: "./runs"
  verbose: true
  pretrained: null
  resume: null
  SEED: 1337
dataset:
  point_cloud:
    params:
      pc_ids_path: "data/TextANIMAR2023/3D_Model_References/References.csv"
      pc_dir: "data/TextANIMAR2023/3D_Model_References/References"
  text:
    params:
      text_queries_path: "data/TextANIMAR2023/Test/TextQuery_Test.csv"
data_loader:
  train:
    params:
      batch_size: 16
      num_workers: 2
      shuffle: true
  val:
    params:
      num_workers: 2
      batch_size: 16
model:
  name: "BaselineModel"
  embed_dim: 128
  xbm:
    enable_epoch: 1000
    memory_size: 1024
trainer:
  lr: 0.001
  use_fp16: false
  debug: false
  num_epochs: 10000
  clip_grad: 10.0
  evaluate_interval: 1
  log_interval: 1
  save_interval: 1000
callbacks:
  - name: ModelCheckpoint
    params:
      filename: "baseline-{epoch}-{train_loss:.4f}-{val_loss:.4f}"
      monitor: "val_loss"
      verbose: True
      save_top_k: 3
      mode: min
